apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ar9dl0t9i-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:372ec10d7d0ef1f0e57890fc0f2bf1d8b13703bc@sha256:b15d310042978576a6b328437d8a92e74fae5b4f3f61f2ca9c4acc1191c5c71e
          name: container-image
